### ISSUE TITLE
Bug: entered unreachable code: every line in hunk has one of '+', '-', or ' ' inserted after parsing

### ISSUE THREAD

**Issue by Piturnah** [Piturnah/gex#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attempted to render the following diff in [piturnah.xyz](https://github.com/piturnah/piturnah.github.io)

```diff
diff --git a/asteroid-loop/index.html b/asteroid-loop/index.html
index d79df71..e2d1e9f 100644
--- a/asteroid-loop/index.html
+++ b/asteroid-loop/index.html
@@ -14,15 +14,10 @@
     var unityInstance = UnityLoader.instantiate("unityContainer", "Build/thing build.json", { onProgress: UnityProgress });
   </script>
   <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
-  <script>
-    $(function () {
-      $("#header").load("/assets/header.html");
-    });
-  </script>
 </head>
 
 <body>
-  <div id="header"></div>
+  <#header />
   <div class="webgl-content">
     <div id="unityContainer" style="width: 960px; height: 540px"></div>
     <div class="footer">
@@ -32,4 +27,4 @@
   </div>
 </body>
 
-</html>
\ No newline at end of file
+</html>
```

### Expected Behavior

The diff should've been plainly rendered

### Environment

```markdown
- OS: NixOS 23.05
- gex 0.6.3-dev (c7d36cf 2023-08-30 14:52:11 +0100)
```

### Anything else?

Backtrace:

```
thread 'main' panicked at 'internal error: entered unreachable code: every line in hunk has one of '+', '-', or ' ' inserted after parsing', src/status.rs:97:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: <&T as core::fmt::Display>::fmt
   3: core::fmt::rt::Argument::fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   4: core::fmt::write
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   5: <gex::status::Status as gex::render::renderer::Render>::render
   6: gex::main
```

**Comment by Piturnah** [comment]
Might have something to do with trailing newline

**Comment by Piturnah** [comment]
Also: this is the kind of thing I mean by #52 :sob:
